/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CompetitionWhereUniqueInput } from "../../competition/base/CompetitionWhereUniqueInput";
import { ValidateNested, IsOptional, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { TeamUpdateManyWithoutTablesInput } from "./TeamUpdateManyWithoutTablesInput";

@InputType()
class TableUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CompetitionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CompetitionWhereUniqueInput)
  @IsOptional()
  @Field(() => CompetitionWhereUniqueInput, {
    nullable: true,
  })
  competition?: CompetitionWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  drawn?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  goalsConceded?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  goalsDifference?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  goalsScored?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  lost?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  played?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  points?: number;

  @ApiProperty({
    required: false,
    type: () => TeamUpdateManyWithoutTablesInput,
  })
  @ValidateNested()
  @Type(() => TeamUpdateManyWithoutTablesInput)
  @IsOptional()
  @Field(() => TeamUpdateManyWithoutTablesInput, {
    nullable: true,
  })
  team?: TeamUpdateManyWithoutTablesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  won?: number;
}

export { TableUpdateInput as TableUpdateInput };
