/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { LiveService } from "../live.service";
import { LiveCreateInput } from "./LiveCreateInput";
import { Live } from "./Live";
import { LiveFindManyArgs } from "./LiveFindManyArgs";
import { LiveWhereUniqueInput } from "./LiveWhereUniqueInput";
import { LiveUpdateInput } from "./LiveUpdateInput";

export class LiveControllerBase {
  constructor(protected readonly service: LiveService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Live })
  async createLive(@common.Body() data: LiveCreateInput): Promise<Live> {
    return await this.service.createLive({
      data: data,
      select: {
        awayGoals: true,
        awayScore: true,
        awayTeam: true,
        awayTeamBadge: true,
        createdAt: true,
        homeGoals: true,
        homeScore: true,
        homeTeam: true,
        homeTeamBadge: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Live] })
  @ApiNestedQuery(LiveFindManyArgs)
  async lives(@common.Req() request: Request): Promise<Live[]> {
    const args = plainToClass(LiveFindManyArgs, request.query);
    return this.service.lives({
      ...args,
      select: {
        awayGoals: true,
        awayScore: true,
        awayTeam: true,
        awayTeamBadge: true,
        createdAt: true,
        homeGoals: true,
        homeScore: true,
        homeTeam: true,
        homeTeamBadge: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Live })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async live(
    @common.Param() params: LiveWhereUniqueInput
  ): Promise<Live | null> {
    const result = await this.service.live({
      where: params,
      select: {
        awayGoals: true,
        awayScore: true,
        awayTeam: true,
        awayTeamBadge: true,
        createdAt: true,
        homeGoals: true,
        homeScore: true,
        homeTeam: true,
        homeTeamBadge: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Live })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateLive(
    @common.Param() params: LiveWhereUniqueInput,
    @common.Body() data: LiveUpdateInput
  ): Promise<Live | null> {
    try {
      return await this.service.updateLive({
        where: params,
        data: data,
        select: {
          awayGoals: true,
          awayScore: true,
          awayTeam: true,
          awayTeamBadge: true,
          createdAt: true,
          homeGoals: true,
          homeScore: true,
          homeTeam: true,
          homeTeamBadge: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Live })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteLive(
    @common.Param() params: LiveWhereUniqueInput
  ): Promise<Live | null> {
    try {
      return await this.service.deleteLive({
        where: params,
        select: {
          awayGoals: true,
          awayScore: true,
          awayTeam: true,
          awayTeamBadge: true,
          createdAt: true,
          homeGoals: true,
          homeScore: true,
          homeTeam: true,
          homeTeamBadge: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
