/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AppSettingService } from "../appSetting.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AppSettingCreateInput } from "./AppSettingCreateInput";
import { AppSetting } from "./AppSetting";
import { AppSettingFindManyArgs } from "./AppSettingFindManyArgs";
import { AppSettingWhereUniqueInput } from "./AppSettingWhereUniqueInput";
import { AppSettingUpdateInput } from "./AppSettingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AppSettingControllerBase {
  constructor(
    protected readonly service: AppSettingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AppSetting })
  @nestAccessControl.UseRoles({
    resource: "AppSetting",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAppSetting(
    @common.Body() data: AppSettingCreateInput
  ): Promise<AppSetting> {
    return await this.service.createAppSetting({
      data: data,
      select: {
        channelLogo: true,
        channelName: true,
        createdAt: true,
        facebook: true,
        id: true,
        instagram: true,
        twiiter: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AppSetting] })
  @ApiNestedQuery(AppSettingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AppSetting",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async appSettings(@common.Req() request: Request): Promise<AppSetting[]> {
    const args = plainToClass(AppSettingFindManyArgs, request.query);
    return this.service.appSettings({
      ...args,
      select: {
        channelLogo: true,
        channelName: true,
        createdAt: true,
        facebook: true,
        id: true,
        instagram: true,
        twiiter: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AppSetting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AppSetting",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async appSetting(
    @common.Param() params: AppSettingWhereUniqueInput
  ): Promise<AppSetting | null> {
    const result = await this.service.appSetting({
      where: params,
      select: {
        channelLogo: true,
        channelName: true,
        createdAt: true,
        facebook: true,
        id: true,
        instagram: true,
        twiiter: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AppSetting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AppSetting",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAppSetting(
    @common.Param() params: AppSettingWhereUniqueInput,
    @common.Body() data: AppSettingUpdateInput
  ): Promise<AppSetting | null> {
    try {
      return await this.service.updateAppSetting({
        where: params,
        data: data,
        select: {
          channelLogo: true,
          channelName: true,
          createdAt: true,
          facebook: true,
          id: true,
          instagram: true,
          twiiter: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AppSetting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AppSetting",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAppSetting(
    @common.Param() params: AppSettingWhereUniqueInput
  ): Promise<AppSetting | null> {
    try {
      return await this.service.deleteAppSetting({
        where: params,
        select: {
          channelLogo: true,
          channelName: true,
          createdAt: true,
          facebook: true,
          id: true,
          instagram: true,
          twiiter: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
